Change 4 - Add Snyk Git Action (#4)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -82,6 +82,56 @@ jobs:
           name: maven-dependency-tree
           path: mvn-dependency-tree.zip
 
+  snyk_scan:
+    needs: [ build_all ]
+    name: Run SCA Snyk Scan
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Download Maven Build
+        uses: actions/download-artifact@v4
+        with:
+          name: maven-build
+          path: .
+
+      - name: Extract Maven Build
+        shell: bash
+        run: tar -xzf maven-build.tgz -C ~
+
+      - name: Setup Node.js Environment
+        uses: actions/setup-node@v4.0.2
+
+      - name: Install Snyk CLI
+        shell: bash
+        run: npm install snyk -g
+
+      # Snyk returns exit code 1 if vulnerabilities are found
+      - name: Run Snyk Scan
+        shell: bash
+        run: |
+          export SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}
+          snyk test --all-projects --dev --sarif-file-output=snyk.sarif --json > snyk.json || EXIT_CODE=$?
+          if [ $EXIT_CODE -eq 1 ]; then exit 0; fi
+
+      - name: Upload Snyk Scan Results
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: snyk-scan-report
+          path: '**/snyk.json'
+
+      - name: Upload Snyk Result To GitHub Code Scanning
+        if: always()
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: snyk.sarif
+          category: snyk-sca-tool
+
   eclipse_steady_scan:
     needs: [ build_all ]
     name: Run SCA Eclipse Steady Scan
